services:
  product.inventory.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: product.inventory.db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - product.inventory.db.volume:/var/opt/mssql
  
  order.management.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: order.management.db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1434:1433"
    volumes:
      - order.management.db.volume:/var/opt/mssql
  
  community.db:
    image: postgres
    container_name: community.db
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=CommunityDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - community.db.volume:/var/lib/postgresql/data/
  
  basket.service.db:
    image: mongo
    container_name: basket.service.db
    restart: always
    environment:
      - TZ=Europe/Kyiv
    ports:
      - "27017:27017"
    volumes:
      - basket.service.db.volume:/data/db
        
  mongo-ui:
    image: mongo-express
    container_name: mongo-ui
    restart: always
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://basket.service.db:27017/
      - ME_CONFIG_BASICAUTH=false
        
  community.cache:
    image: redis
    container_name: community.cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  product.inventory.db.volume:
  order.management.db.volume:
  basket.service.db.volume:
  community.db.volume: